project:
  type: website
  output-dir: docs

bibliography: eapd.bib
reference-location: margin

website:
  navbar:
    tools:
      - icon: globe
        href: https://policy.desa.un.org/
    left:
      - text: "Home"
        href: index.qmd
      - text: "About Us"
        href: about.qmd
      - text: WEFM
        href: WEFM.qmd
      - text: "Publications"
        href: "https://policy.desa.un.org/unit/global-economic-monitoring-unit"
        target: "_blank"
    logo: "static/GEMB.png"
  favicon: "static/favicon.ico"
  page-footer:
    background: "#333333"
    left: "Â© United Nations Department of Economic and Social Affairs"
    border: "#009edb"
  search: false



theme: 
  - brand
  - styles.scss

